- name: creates the cloud infra
#  hosts: all
#  tasks:
#    - name: ?????????????????????????????????????????

- name: Setup web server
  hosts: localhost
  user: centos
  become: True
  gather_facts: True
  vars:
    # ansible_ssh_user=centos
    ansible_ssh_private_key_file: ./carmel-keypem.pem
  vars_files:
    - group_vars/env
    - group_vars/colman.env
    - group_vars/docker.env
  tasks:
    - name: install necessary packages
