- name: creates the cloud infra
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        key_name: carmel-keypem
        instance_type: t2.micro
        image_id: ami-0e86e20dae9224db8 
        wait: yes
        region: us-east-1
        count: 1
        network_interfaces:
          - assign_public_ip: true
        vpc_subnet_id: subnet-0f748f67d5a99439f
        security_groups:
          - sg-0dcf9dad4dc751acb
        tags:
          Name: carmels-app
        user_data: |
          #!/bin/bash
          useradd -m -s /bin/bash centos
          usermod -aG sudo centos
          mkdir /home/centos/.ssh
          chmod 700 /home/centos/.ssh
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnn0ENe1E3nEaz41qQT7o1Mw36KeEtk2nMgKWcUmxm8fpLiHiJcu+VYyfAm2B/WiDzrXHT5kDd21ncd4wfu9oVVGQefFTJ0iT7QwpS/OpG1LeqnbvpfdngWUGSe+PHFdTF4/nfwhbLrj+YiKlwg++YWaz/PVYlOXqXZlcCa7ly7fSIz+XP2OiQ64HePRunDkAZ2pFx0D+3ptE/3AzBLzz3RYP+mCvKr/R1kXtMDyQaG5sV4XwGA9AK6bPgrQziZnEUcZQpzcwtkQHYqvhLv4jF74diLfoNWvK2ytbUxb7lvZUqMm5Y2pqU343aap7HItprUa7HECmROTbq3p4brT/B carmel-keypem" >> /home/centos/.ssh/authorized_keys
          chmod 600 /home/centos/.ssh/authorized_keys
          chown -R centos:centos /home/centos
          echo "centos ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        state: present
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.network_interfaces[0].association.public_ip }}"
        groupname: app-server
      with_items: "{{ ec2.instances }}"

    - name: Pause for 30 seconds to ensure the instance is fully up
      ansible.builtin.pause:
        seconds: 30

- name: Setup web server
  hosts: app-server
  user: centos
  become: True
  gather_facts: True
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: latest
        update_cache: true

    - name: Ensure docker deamon is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      become: true
