- name: creates the cloud infra
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        key_name: carmel-keypem
        instance_type: t2.micro
        image_id: ami-0e86e20dae9224db8 
        wait: yes
        region: us-east-1
        count: 1
        network_interfaces:
          - assign_public_ip: true
        vpc_subnet_id: subnet-0f748f67d5a99439f
        security_groups:
          - sg-0dcf9dad4dc751acb
        tags:
          Name: carmels-app
        state: present
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.network_interfaces[0].association.public_ip }}"
        groupname: app-server
      with_items: "{{ ec2.instances }}"

#- name: Setup web server
#  hosts: localhost
#  user: centos
#  become: True
#  gather_facts: True
#  vars:
#     ansible_ssh_user=centos
#     ansible_ssh_private_key_file: ./carmel-keypem.pem
#  vars_files:
#    - group_vars/env
#    - group_vars/colman.env
#    - group_vars/docker.env
#  tasks:
#    - name: install necessary packages
